# spring:
#   jpa:
#     show-sql: "true"
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: "org.hibernate.dialect.MySQL5Dialect"
#   database:
#     driverClassName: "com.mysql.jdbc.Driver"
#   datasource:
#     url: "jdbc:mysql://localhost:32771/itemsharingdatabase"
#     username: "root"
#     password: ""
#     testWhileIdle: true
#     validationQuery: "SELECT 1"
#        
# security:
#   basic:
#     enable: false
#     
# server:
#   port: 8081